spring:
  datasource:
    url: jdbc:mysql://localhost:3306/srbademoDb
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

